spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/to_do_db
    username: annakulova
    password: db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
